title: Just In Case
description: A Resource Hub for Feds and Associated Folk
theme: just-the-docs

url: https://git-sci.github.io/

aux_links:
  GitHub Repository: https://github.com/git-sci/git-sci.github.io
